### ISSUE TITLE
[Proposal] Laravel e Lumen Docs

### ISSUE THREAD

**Issue by vluzrmos** [artesaos/proposals#1]
Starts an oficial Laravel Brasil documentation of Laravel and Lumen frameworks. It will be available on artesaos.org/laravel/docs and artesaos.org/lumen/docs using the same style of laravel.com/docs.

**Comment by mthlima** [comment]
:+1: awesome

**Comment by williamoliveira** [comment]
:+1:

**Comment by hernandev** [comment]
:+1:

**Comment by gilvaju** [comment]
:+1:

**Comment by hernandev** [comment]
Project started at https://github.com/artesaos/laravel-docs

First, we will start translating the Laravel docs and only then start with Lumen ones.

Please wait the guidelines to send your pull request
